/*
 * This source file was generated by the Gradle 'init' task
 */
package jraffic;

import javafx.animation.AnimationTimer;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.Background;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;

public class App extends Application{
    private final double SPEED = 0.1;
    private final int WIDTH = 800;
    private final int HEIGHT = 800;
    private final int CAR_SIZE = 40;
    @Override
    public void start(Stage primaryStage) throws Exception {

        Pane pane= new Pane();
        pane.setBackground(Background.fill(Color.BLACK));
        Rectangle rectangle = new Rectangle(10.,10.,CAR_SIZE,CAR_SIZE);
        rectangle.setFill(Color.RED);
        AnimationTimer loop = new AnimationTimer() {
            @Override
            public void handle(long now) {
                double currentX = rectangle.getX();
                if (currentX >= (WIDTH - CAR_SIZE)){
                    rectangle.setX(10);
                }else{
                    rectangle.setX(currentX+SPEED);
                }
            }
        };

        loop.start();
        pane.getChildren().add(rectangle);
        Scene scene = new Scene(pane, 800,800);
        primaryStage.setScene(scene);
        primaryStage.setResizable(false);
        primaryStage.show();
        
    }
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        launch();
        System.out.println("start");
    }
}
